FROM node:16.12.0-alpine

WORKDIR /usr/src/app/

# Install app dependencies
COPY package*.json ./
RUN npm install 
RUN npm install react-scripts@3.4.1 -g 

# Add app
COPY . .

# start app
EXPOSE 3000
CMD ["npm", "start"]