version: '3'

services:
  react-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: react_dev
    environment:
      env_file: .env
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  
  react-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: react_prod
    environment:
      env_file: .env
      NODE_ENV: production
    ports:
      - "3000:80"

  