# Building Stage
FROM node:16.12.0-alpine as builder

WORKDIR /usr/src/app/
COPY package*.json ./
RUN npm install 
RUN npm install react-scripts@3.4.1 -g 
COPY . .
RUN npm run build

# Production Stage
FROM nginx:1.23.1-alpine

COPY --from=builder /usr/src/app/build /usr/share/nginx/html